#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt -y update
sudo apt -y install nginx
sudo ufw -y app list
sudo ufw -y allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service restart nginx
