#!/usr/bin/env bash
# Installs, configures, and starts the server
# Imanol Asolo
apt-get update
apt-get install -y nginx
chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
