#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver XX-web-01 54.237.25.95:80 check\n\tserver 132333-web-02 54.90.60.135:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
